server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
batch:
  job:
    enabled: false
    names: checkMgtJob

spring:
  datasource:
    common:
      jdbcUrl: jdbc:log4jdbc:mariadb://localhost:3306/monkey?useSSL=false&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
      driverClassName: org.mariadb.jdbc.Driver
      username: root
      password: qwer1234
    trade:
      jdbc-url: jdbc:mariadb://localhost:3306/monkey?useSSL=false&serverTimezone=UTC
      driverClassName: org.mariadb.jdbc.Driver
      username: root
      password: qwer1234
    admin:
      jdbc-url: jdbc:mariadb://localhost:3306/monkey?useSSL=false&serverTimezone=UTC
      driverClassName: org.mariadb.jdbc.Driver
      username: root
      password: qwer1234


